### ISSUE TITLE
Forge 1.20.1

### ISSUE THREAD

**Issue by MartinRakus** [GreenhouseTeam/rapscallions-and-rockhoppers#8] opened 2024-03-04 22:50 UTC
Any plans of adding a Forge version? Would love to see those little penguins on my 1.20.1 Forge server.

**Comment by ChrysanthCow** [comment] 2024-03-04 23:04
Technically a duplicate of #7. I'd want to fix issues with the penguin ai first before I consider backporting.

**Comment by MartinRakus** [comment] 2024-03-04 23:15
The backport to version 1.20.1 is not the important part, main part of my question was Forge support, but I understand.

**Comment by ChrysanthCow** [comment] 2024-06-04 00:03
Not happening due to rewrites to the codebase for 1.21.

**Closed as not planned** 2024-06-04 00:03 UTC
